### PR TITLE
translate 11-notifications to CN

### PR DESCRIPTION
**Pull request by yren**
translate 11-notifications to CN

### CODE REVIEW

**Comment by zhe** [comment]
Hi, yren, how could we see those changes on http://zh.discovermeteor.com/chapters/notifications/?

**Comment by yren** [comment]
这个需要去跑一下项目 DiscoverMeteorStatic ， 这个是 Middleman generator. 跑完 http://zh.discovermeteor.com 就会更新了。我猜有个定时任务，或需要 SachaG 手工做一下。我也是新手，具体不大清楚。不过，你可以在本地跑一下 DiscoverMeteorStatic ，就能看到更新了。步骤如下：
$git clone git@github.com:DiscoverMeteor/DiscoverMeteorStatic.git
$cd DiscoverMeteorStatic
$bundle install
$git submodule init
## for first time
$git submodule update
$git submodule foreach git pull origin master
$export DMLANG=zh
$bundle exec middleman

**Comment by yren** [comment]
Hi, @SachaG 
       Does the project DiscoverMeteorStatic running is a cron job or need you manual trigger it to update http://zh.discovermeteor.com

**Comment by SachaG** [comment]
You need to trigger it manually, sorry. I know it's not a great system…

**Comment by yren** [comment]
ok, it's good enough :)

**Pull request merged**
